### ISSUE TITLE
cannot find firmware-imx recipe with kobo-clara-hd distro

### ISSUE THREAD

**Issue by akemnade** [kevinior/meta-kobo-clara-hd#1]
$ bitbake clara-image-core
Loading cache: 100% |############################################| Time: 0:00:01
Loaded 3483 entries from dependency cache.
ERROR: No recipes available for:
  /home/andi/imx-yocto-bsp2/sources/meta-kobo-clara-hd/recipes-bsp/firmware-imx/firmware-imx_8.8.bbappend

Summary: There was 1 ERROR message shown, returning a non-zero exit code.

Env was set up this way:
MACHINE=kobo-clara-hd DISTRO=kobo-clara-hd source setup-environment build

**Comment by kevinior** [comment]
What does your `bitbake-layers show-layers` output look like? I get:
```
layer                 path                                      priority
==========================================================================
meta                  /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/poky/meta  5
meta-poky             /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/poky/meta-poky  5
meta-oe               /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-openembedded/meta-oe  6
meta-multimedia       /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-openembedded/meta-multimedia  6
meta-python           /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-openembedded/meta-python  7
meta-freescale        /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-freescale  5
meta-freescale-3rdparty  /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-freescale-3rdparty  4
meta-freescale-distro  /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-freescale-distro  4
meta-bsp              /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-imx/meta-bsp  8
meta-sdk              /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-imx/meta-sdk  8
meta-ml               /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-imx/meta-ml  8
meta-browser          /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-browser  7
meta-rust             /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-rust  7
meta-gnome            /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-openembedded/meta-gnome  7
meta-networking       /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-openembedded/meta-networking  5
meta-filesystems      /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-openembedded/meta-filesystems  6
meta-qt5              /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-qt5  7
meta-python2          /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-python2  7
meta-kobo-clara-hd    /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-kobo-clara-hd  91
meta-rauc             /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-rauc  6
workspace             /home/kevin/reps/imx-linux-5.4.24_2.1.0/bld-clara-fb/workspace  99
```

Although I'm sure some of those aren't necessary (meta-browser and meta-rust in particular).

According to `bitbake-layers show-appends firmware-imx` and `bitbake-layers show-recipes -f firmware-imx` it's using sources/meta-imx/meta-bsp/recipes-bsp/firmware-imx/firmware-imx_8.8.bb for firmware-imx.

At the weekend I'm hoping to have time to do a clean set up of meta-kobo-clara-hd (with the current released BSP from NXP) and make careful notes so that I can document the setup.

**Comment by akemnade** [comment]
On Wed, 07 Apr 2021 10:52:28 -0700
kevinior ***@***.***> wrote:

> What does your `bitbake-layers show-layers` output look like? I get:
> ```
> layer                 path                                      priority
> ==========================================================================
> meta                  /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/poky/meta  5
> meta-poky             /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/poky/meta-poky  5
> meta-oe               /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-openembedded/meta-oe  6
> meta-multimedia       /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-openembedded/meta-multimedia  6
> meta-python           /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-openembedded/meta-python  7
> meta-freescale        /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-freescale  5
> meta-freescale-3rdparty  /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-freescale-3rdparty  4
> meta-freescale-distro  /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-freescale-distro  4
> meta-bsp              /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-imx/meta-bsp  8
> meta-sdk              /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-imx/meta-sdk  8
> meta-ml               /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-imx/meta-ml  8
> meta-browser          /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-browser  7
> meta-rust             /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-rust  7
> meta-gnome            /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-openembedded/meta-gnome  7
> meta-networking       /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-openembedded/meta-networking  5
> meta-filesystems      /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-openembedded/meta-filesystems  6
> meta-qt5              /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-qt5  7
> meta-python2          /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-python2  7
> meta-kobo-clara-hd    /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-kobo-clara-hd  91
> meta-rauc             /home/kevin/reps/imx-linux-5.4.24_2.1.0/sources/meta-rauc  6
> workspace             /home/kevin/reps/imx-linux-5.4.24_2.1.0/bld-clara-fb/workspace  99
> ```
> 
~/imx-yocto-bsp2/build$ bitbake-layers show-layers
NOTE: Starting bitbake server...
layer                 path                                      priority
==========================================================================
meta                  /home/andi/imx-yocto-bsp2/sources/poky/meta  5
meta-poky             /home/andi/imx-yocto-bsp2/sources/poky/meta-poky  5
meta-oe               /home/andi/imx-yocto-bsp2/sources/meta-openembedded/meta-oe  6
meta-multimedia       /home/andi/imx-yocto-bsp2/sources/meta-openembedded/meta-multimedia  6
meta-python           /home/andi/imx-yocto-bsp2/sources/meta-openembedded/meta-python  7
meta-kobo-clara-hd    /home/andi/imx-yocto-bsp2/sources/meta-kobo-clara-hd  91
meta-rauc             /home/andi/imx-yocto-bsp2/sources/meta-rauc  6
meta-freescale        /home/andi/imx-yocto-bsp2/sources/meta-freescale  5
meta-freescale-3rdparty  /home/andi/imx-yocto-bsp2/sources/meta-freescale-3rdparty  4
meta-freescale-distro  /home/andi/imx-yocto-bsp2/sources/meta-freescale-distro  4


> Although I'm sure some of those aren't necessary (meta-browser and meta-rust in particular).
> 
> According to `bitbake-layers show-appends firmware-imx` and `bitbake-layers show-recipes -f firmware-imx` it's using sources/meta-imx/meta-bsp/recipes-bsp/firmware-imx/firmware-imx_8.8.bb for firmware-imx.

hmm, adding stuff:

~/imx-yocto-bsp2/build$ bitbake-layers add-layer ~/imx-yocto-bsp2/sources/meta-imx/meta-bsp
NOTE: Starting bitbake server...
~/imx-yocto-bsp2/build$ bitbake clara-image-core                                           
WARNING: /home/andi/imx-yocto-bsp2/sources/meta-kobo-clara-hd/recipes-python/haslate/haslate_1.0.0.bb: Un
able to get checksum for haslate SRC_URI entry authorized_keys: file could not be found
ERROR: ParseError at /home/andi/imx-yocto-bsp2/sources/meta-imx/meta-bsp/recipes-kernel/kernel-modules/ke
rnel-module-pcie8997.bb:1: Could not include required file recipes-connectivity/nxp-wlan-sdk/nxp-wlan-sdk
_git.inc

Summary: There was 1 WARNING message shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
~/imx-yocto-bsp2/build$ bitbake-layers add-layer ~/imx-yocto-bsp2/sources/meta-imx/meta-   
meta-bsp/ meta-ml/  meta-sdk/
~/imx-yocto-bsp2/build$ bitbake-layers add-layer ~/imx-yocto-bsp2/sources/meta-imx/meta-sdk
/
classes/              recipes-benchmark/    recipes-extended/     recipes-multimedia/
conf/                 recipes-connectivity/ recipes-fsl/          recipes-sato/
dynamic-layers/       recipes-devtools/     recipes-graphics/     recipes-support/
~/imx-yocto-bsp2/build$ bitbake-layers add-layer ~/imx-yocto-bsp2/sources/meta-imx/meta-sdk
NOTE: Starting bitbake server...
~/imx-yocto-bsp2/build$ bitbake clara-image-core                                           
WARNING: /home/andi/imx-yocto-bsp2/sources/meta-kobo-clara-hd/recipes-python/haslate/haslate_1.0.0.bb: Un
able to get checksum for haslate SRC_URI entry authorized_keys: file could not be found
Parsing recipes: 100% |###################################################################| Time: 0:01:16
Parsing of 2457 .bb files complete (0 cached, 2457 parsed). 3602 targets, 262 skipped, 1 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'networkmanager' (but /home/andi/imx-yocto-bsp2/sources/meta-kobo-clara-hd/recipes-images/images/clara-image-core.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'networkmanager' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['networkmanager']
ERROR: Required build target 'clara-image-core' has no buildable providers.
Missing or unbuildable dependency chain was: ['clara-image-core', 'networkmanager']

Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
~/imx-yocto-bsp2/build$ bitbake-layers add-layer ~/imx-yocto-bsp2/sources/meta-openembedded/meta-networking
NOTE: Starting bitbake server...
***@***.***:~/imx-yocto-bsp2/build$ bitbake clara-image-core                                           
WARNING: /home/andi/imx-yocto-bsp2/sources/meta-kobo-clara-hd/recipes-python/haslate/haslate_1.0.0.bb: Un
able to get checksum for haslate SRC_URI entry authorized_keys: file could not be found

At least it is building something.
> 
> At the weekend I'm hoping to have time to do a clean set up of meta-kobo-clara-hd (with the current released BSP from NXP) and make careful notes so that I can document the setup.
> 
BTW: Do we really need anything in the original firmware-imx? 
At least the system works without that sdma thing.

**Comment by akemnade** [comment]
ok, got till here:

| + cp Module.symvers /home/andi/imx-yocto-bsp2/build/tmp/work-shared/kobo-clara-hd/kernel-build-artifacts/
| cp: cannot stat 'Module.symvers': No such file or directory

probably no make modules was done in the kernel
and there is
#              If the defconfig file was created with make_savedefconfig, 
#              not all options are specified, and should be restored with their
#              defaults, not set to 'n'. To properly expand a defconfig like
#              this, specify: KCONFIG_MODE="--alldefconfig" in the kernel
#              recipe.
kobo_defconfig was created with make savedefconfig.

I will better wai for you to document the process before flooding you with tickets.

**Comment by kevinior** [comment]
I guess with your kernels there's no need for most (all?) of the stuff from NXP's layers. IIRC I'm appending to the firmware-imx recipe to copy the EPDC config blob into the right place but I could make my own recipe for that.

The `Unable to get checksum for haslate SRC_URI entry authorized_keys: file could not be found` is because you need to add your own authorized_keys file for that recipe. I mentioned that in the README.

What I definitely forgot to mention in the README (because I'd forgotten I did it) is a patch to kernel.bbclass. In your sources/poky you'll need to apply:
```diff
--- a/meta/classes/kernel.bbclass
+++ b/meta/classes/kernel.bbclass
@@ -452,7 +452,7 @@ do_shared_workdir () {
 
        # Copy files required for module builds
        cp System.map $kerneldir/System.map-${KERNEL_VERSION}
-       cp Module.symvers $kerneldir/
+       [ -e Module.symvers ] && cp Module.symvers $kerneldir/
        cp .config $kerneldir/
        mkdir -p $kerneldir/include/config
        cp include/config/kernel.release $kerneldir/include/config/kernel.release
```

I vaguely remember that I found that fix in a mailing list and it's not needed for newer Yocto versions. I'll update the documentation to add that.

The KCONFIG_MODE thing might explain why basing the kernel recipe on linux-yocto-custom didn't work for me. Thanks for the info.

Sorry you've hit so many problems. I'll work on setting up my Yocto system from scratch at the weekend and fix the documentation. Thanks for the help.

**Comment by kevinior** [comment]
I've finally got the newer NXP BSP working (after a lot of distractions kept me from working on this) and added some [install instructions](https://github.com/kevinior/meta-kobo-clara-hd/blob/main/install.md).
